# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 072e25c6878a79f7e2d50edc23ada984e6ffdda273c960540c5ce4368d90c91d6802d084bf9cb5606a8548898e372f7d2f8d70d2d57fe602f0c6ed1fa63f1e1c

test:
  secret_key_base: d4d88517b6678f8daa2509ca6dced910769f38ad5c85e677ec5cb00f4c28c06fc4eeff205217d7e16048660aee6875f35cea27e16239eccca246faa174e73eca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
